export enum LoadImageTypes {
  FETCH_IMAGES = "FETCH_IMAGES",
  FETCH_IMAGES_SUCCESS = "FETCH_IMAGES_SUCCESS",
  FETCH_IMAGES_FAILURE = "FETCH_IMAGES_FAILURE",
  DELETE_IMAGE = "DELETE_IMAGE"
}

export enum NavigationTypes {
  GET_PAGE_NAME = "GET_PAGE_NAME",
  CHANGE_PAGE = "CHANGE_PAGE",
  GET_PREVIOUS = "GET_PREVIOUS"
}

export enum ModalTypes {
  OPEN_MODAL = "OPEN_MODAL"
}